### ISSUE TITLE
Fatal error in build_runner caused by angular_compiler

### ISSUE THREAD

**Issue by dineshbhosale** [dart-lang/angular#1148]
contents of `pubspec.yaml` file

```yaml
name: testtt
description:
version: 0.0.1

environment:
  sdk: '>=2.0.0-dev.28.0 <2.0.0'

dependencies:
  angular: 5.0.0-alpha+7
  #angular_forms: ^2.0.0-alpha
  angular_router: ^2.0.0-alpha+7
  angular_components: 0.9.0-alpha+7

dev_dependencies:
  build_runner: ^0.8.0
  #build_test: ^0.10.0
  build_web_compilers: ^0.3.0
  build_config: ^0.2.4
```

Output of `pub run build_runner serve`

```bash
[INFO] Generating build script completed, took 241ms


You have hit a bug in build_runner
Please file an issue with reproduction steps at https://github.com/dart-lang/build/issues


'package:angular/builder.dart': error: line 29 pos 42: invalid arguments passed to constructor 'CompilerFlags' for class 'CompilerFlags': no optional formal parameter named 'useAstPkg'
const _defaultFlags = const CompilerFlags(
                                         ^

package:build_runner/src/package_graph/apply_builders.dart 150:37  new BuilderApplication.forBuilder.<fn>.<fn>
package:build_runner/src/package_graph/apply_builders.dart 261:27  _createBuildPhasesForBuilderInCycle.<fn>.<fn>
dart:core                                                          List.addAll
package:build_runner/src/package_graph/apply_builders.dart 215:7   createBuildPhases
package:build_runner/src/generate/watch_impl.dart 91:13            watch
package:build_runner/src/generate/build.dart 124:5                 watch
package:build_runner/src/entrypoint/options.dart 346:25            _ServeCommand.run
package:args/command_runner.dart 194:27                            CommandRunner.runCommand
package:args/command_runner.dart 109:29                            CommandRunner.run.<fn>
dart:async                                                         new Future.sync
package:args/command_runner.dart 109:11                            CommandRunner.run
package:build_runner/src/entrypoint/run.dart 15:24                 run
.dart_tool/build/entrypoint/build.dart 54:22                       main
```

Sample:
https://github.com/dineshbhosale/ng5-test
