### ISSUE TITLE
Removal of dependency_overrides causes unable to find runApp

### ISSUE THREAD

**Issue by no-if** [dart-lang/angular#1201]
```
name: examples.hello_world_no_reflector

environment:
  sdk: ">=2.0.0-dev.32.0 <2.0.0"

dependencies:
  angular: ^5.0.0-alpha

dev_dependencies:
  build_runner: ^0.8.0
  build_test: ^0.10.1+1
  build_web_compilers: ^0.3.4+1

# DO NOT REMOVE. We don't publish this package, it is just for testing.
# dependency_overrides:
#   angular:
#     path: ../../angular
#   angular_ast:
#     path: ../../angular_ast
#   angular_compiler:
#     path: ../../angular_compiler

```

`The function 'runApp' isn't defined.`
