### ISSUE TITLE
Cannot import CSS files from another package using @import with the package URI

### ISSUE THREAD

**Issue by jolleekin** [dart-lang/angular#1230]
## Setup
In `falcon2/lib/src/dashboard/dashboard_page.css`:
``` css
@import 'package:kin2/css/page.css';

:host {
    padding: 0 var(--padding);
}
```

In `kin2/lib/css/page.css`:
``` css
:host {
    display: flex;
    flex-direction: column;
    position: absolute;
    bottom: 0;
    left: 0;
    right: 0;
    top: 0;
}
```

The generated CSS shim file:
``` dart
library asset_falcon2_lib_src_dashboard_dashboard_page.css.shim.dart;


import 'packages/kin2/css/page.css.shim.dart' as import0;
const List<dynamic> styles = const [
  '._nghost-%COMP% { padding:0 var(--padding); }',import0.styles
]
;
```

## Errors
- The reported error is
```
[SEVERE] build_web_compilers|entrypoint on web/main.dart:
 Unable to find modules for some sources, check the following imports
:

`import 'packages/kin2/css/page.css.shim.dart' as import0;` from falc
on2|lib/src/dashboard/dashboard_page.css.shim.dart at 4:1
```
- The error persists even if the `@import` is commented out
- The order of the styles in incorrect. The imported styles should appear before (have lower priority than) the local styles

## System Info
- Dart SDK: 2.0.0-dev.46.0
- AngularDart: 5.0.0-alpha+9
- Window 10 64bit
- Chrome

**Comment by leonsenft** [comment]
Was this example working for you on a previous version? This might be a regression of https://github.com/dart-lang/angular/issues/39.

**Comment by jolleekin** [comment]
I didn't try it on a previous version. I just started with Angular.

**Comment by leonsenft** [comment]
Okay no worries, I'll look into this.

**Comment by alorenzen** [comment]
This is definitely a "feature" that isn't used very often. I didn't even know we supported this until you filed the bug.

Most clients use SASS to do preprocessing of CSS before feeding into angular. So in this case, you would let SASS handle the import, not Angular.

**Comment by matanlurey** [comment]
@alorenzen: Definitely, but I think it's reasonable to keep this working at least through 5.x.

**Comment by leonsenft** [comment]
https://github.com/dart-lang/angular/pull/1279 will fix the order issue. Looking at the package URL issue now.

The reason the error continues when you comment out the import is because the compiler uses a regex to extract the `@import` strings rather than fully parsing the CSS, so it can't distinguish whether it's inside a comment or not. We probably won't bother fixing this for now, but it's worth considering when we solidify our CSS parsing story here https://github.com/dart-lang/angular/issues/1252.

**Comment by leonsenft** [comment]
The fix for resolving `@import` URLs from another package will be landing shortly.

It's worth mentioning that if you're importing CSS from another package, you'll have to inform the build system to run the `angular` builder on that package. Angular generates a `.css.dart` (or `.css.shim.dart`) file for each corresponding `.css` file imported by a component. By placing a `@import` in such a file, the compiler will be expecting the corresponding `.css.dart` file to have been generated. If the package this file originates from doesn't produce the corresponding file, compilation will fail.

So if you're importing `@import 'package:kin2/css/page.css';`, one of the following conditions must be met

1. The `kin2` package must depend on `angular`, which will implicitly configure the `angular` builder to run on its CSS. This makes sense if the `kin2` package has its own components.

    ```yaml
    # kin2/pubspec.yaml
    name: kin2
    dependencies:
      angular: ^5.0.0-alpha+12
    ```

2. The `kin2` package must explicitly configure the `angular` builder to run on its CSS via a `build.yaml`. This option makes sense if the `kin2` package itself doesn't have any components, but is expected to be imported by a package with components.

    ```yaml
    # kin2/build.yaml
    targets:
      $default:
        builders:
          angular|angular:
            generate_for:
            - lib/**.css
    ```
3. The package importing CSS from the `kin2` package configures the `angular` builder to run on the CSS via `kin2.build.yaml`. This makes sense if you can't author changes in the `kin2` package to add the `build.yaml` there instead.

    ```yaml
    # kin2.build.yaml
    targets:
      kin2:
        builders:
          angular|angular:
            generate_for:
            - lib/**.css
    ```

I believe the third option is discouraged, because if `kin2` ever did define any builders (or already does), they'll be ignore and overridden by your custom `kin2.build.yaml`.

Finally, if you're going to this much trouble to import CSS cross package, we'd highly recommend you look into using Sass with sass_builder which is widely used by AngularDart users.
