### ISSUE TITLE
Where should pageloader bindings/examples live?

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular#1319]
For context, here is ~approximately the code required to use `angular_test`+`pageloader`:

```dart
NgTestFixture testFixture = ...;

final pageLoader = new HtmlPageLoaderElement.createForElement(
  testFixture.rootElement,
  externalSyncFn: testFixture.update,
)

// You can now use `pageLoader`.
```

## Option 1: No where. Just publish at least one example of using it.

Basically, something like the above. It's about ~3 lines of boilerplate, at most.

## Option 2: Create `angular_pageloader` package with a helper:

```dart
HtmlPageLoaderElement pageLoader(NgTestFixture<void> testFixture) => ...
```

## Option 2B: Same, but inside of `angular_components_test`

... which will be needed *anyway* to host page objects and testing infra.

## Option 3: Add a `pageLoader` function to `NgTestFixture`:

(We used to do this with PL2)

```dart
abstract class NgTestFixture<T> {
  HtmlPageLoaderElement pageLoader() => ...
}
```

This would include:

```yaml
dependencies:
  build: ^0.12.0
  built_value: ^5.1.0
  matcher: ^0.12.0+1
  quiver: ^0.29.0
  source_gen: ^0.8.0
  webdriver: ^2.0.0-beta
```

... as dependencies on every package that uses `angular_test`.
