### ISSUE TITLE
Fails to execute script, because its MIME type ('text/plain') is not executable.

### ISSUE THREAD

**Issue by siliconsorcery** [dart-lang/angular#1412]
Following the [Get Started](https://webdev-dartlang-org-dev.firebaseapp.com/guides/get-started) guide for Angular 5.0.0-alpha+14 and Dart 2.

* [ ] Dart SDK Version (`dart --version`)
Dart VM version: 2.0.0-dev.62.0 (Wed Jun 13 16:50:22 2018 +0200) on "macos_x64"

* [ ] AngularDart Version (i.e. `4.0.0`, `5.0.0-alpha+5`, `MASTER`)
Angular 5.0.0-alpha+14

* [ ] Whether you are using Windows, macOS, or Linux (if applicable)
macOS

* [ ] Whether you are using Chrome, Safari, Firefox, Edge (if applicable)
Chrome

* [ ] Any other packages or constraints we should know about
Using the CLI tools, webdev & stagehand.

## pubspec.yaml
```
name: angular_app
description: A web app that uses AngularDart 
version: 0.0.1

environment:
  sdk: '>=2.0.0-dev.56.0 <=2.0.0-dev.62.0'

dependencies:
  angular: ^5.0.0-alpha+14

dev_dependencies:
  angular_test: ^2.0.0-alpha
  build_runner: ^0.8.9
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
  test: ^0.12.30
```

## pub get
```
Resolving dependencies...
Overriding the upper bound Dart SDK constraint to <=2.0.0-dev.62.0 for the 
following packages:
...
```
webdev serve
## Errors from Chrome Inspector
```
main.dart.js:1 Failed to load resource: the server responded with a 
status of 404 (Not Found)

localhost/:1 Refused to execute script from 'http://localhost:8080/main.dart.js' 
because its MIME type ('text/plain') is not executable, and strict MIME type 
checking is enabled.
```
## Result 
The 'todo' example never stops displaying 'Loading...'
