### ISSUE TITLE
The bound output click does not exist on any directives or on the element (5.0.0-beta)

### ISSUE THREAD

**Issue by montyr75** [dart-lang/angular#1483]
Dart SDK: 2.0.0-dev.68
AngularDart: 5.0.0-beta
Windows 10
Chrome Version 67.0.3396.99 (Official Build) (64-bit)
WebStorm 2018.1.5

Ever since updating to the 5.0 beta, I'm getting this warning on all my template click handlers: 
```
The bound output click does not exist on any directives or on the element.
```
 It happens whenever `(click)` is on a standard HTML element, like a `<button>`. 

These warnings show up in the `Dart Analysis` panel of WebStorm.

**Comment by jheyne** [comment]
I see similar complaints for 
- _change_ on **input** elements
- _input_ on **textarea** elements
- _click_ on **div** elements

Despite the warnings, the listeners work as expected.

**Comment by enyo** [comment]
Can confirm. Seeing the same warnings now after upgrading to the beta.

**Comment by sestegra** [comment]
I have many thousands of these warnings that pollute dart analyzer output.

Would you mind to fix that issue asap, please ?

**Comment by matanlurey** [comment]
Hi all. We are making the call whether or not to disable the plugin initially for v5.

You can do that manually without us though, simply:
```yaml
analyzer:
  exclude: [build/**]
  errors:
    uri_has_not_been_generated: ignore
  plugins:
    - angular # Comment out or remove this line and restart your IDE
```

(reference: https://github.com/dart-lang/stagehand/issues/561)
