### ISSUE TITLE
Using of use_legacy_style_encapsulation flag

### ISSUE THREAD

**Issue by bunopus** [dart-lang/angular#1668]
Hello

With flag `use_legacy_style_encapsulation` one can change default Angular style encapsulation and switch it back to pre-3.0 behaviour by adding this in `build.yaml`
```yaml
global_options:
  angular|angular:
    options:
      use_legacy_style_encapsulation: true

```
According to this commit https://github.com/dart-lang/angular/commit/7fd2bd2b53e7c6dade832662edadd6b47dc0a9e4
this flag will be removed:
> **DEPRECATED**: Support for this flag will be removed in a future release.

But right now this page is gone, and i can't find information about this flag. Can we still using it, or it's not safe and it will be removed soon?
Thanks
