### ISSUE TITLE
Is deferred loading not supported by webdev build?

### ISSUE THREAD

**Issue by stephan-gruen** [dart-lang/angular#1686]
```
<div *ngIf="loginStatus == '2'">
	<geo-users-app @deferred></geo-users-app>
</div>
```
	
```
dependencies:
  angular: ^5.1.0
  angular_components: ^0.10.0

dev_dependencies:
  angular_test: ^2.1.0
  build_runner: ^1.1.2
  build_test: ^0.10.3+3
  build_web_compilers: ^0.4.4+3
  test: ^1.3.4	
```

Build with  
"D:\dart-sdk\dart-sdk 2.2.0-dev.0.0\bin\pub.bat" global run webdev build --output=web:build

As I just noticed the output is now only one file: main.dart.js 

Prior to dart 2 the component I want to lazy load was transpiled to a second file called main.dart.js_1.part.js

Do I have to add a directive now? Is it no longer supported? It is a bug?

**Comment by leonsenft** [comment]
I just confirmed that `@deferred` is working properly on the latest stable releases (SDK 2.1.0).

```yaml
environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  angular: ^5.2.0
  angular_components: ^0.11.0

dev_dependencies:
  angular_test: ^2.2.0
  build_runner: ^1.1.2
  build_test: ^0.10.3
  build_web_compilers: ^1.0.0
  test: ^1.5.1
```

It's possible there was or is a regression in SDK 2.2.0-dev. We should follow up with the SDK to make sure such a regression does not make it to stable.
