### ISSUE TITLE
No provider found for dynamic Component -> dynamic  (Location inject)

### ISSUE THREAD

**Issue by insinfo** [dart-lang/angular#1847]
I updated my angularDart project to dart 2.4.0 and now I can no longer inject Location into the Component Constructor.
I just remove the location of the constructor that stops giving the exception

* [ ] Dart SDK Version 2.4.0
* [ ] AngularDart Version 5
* [ ] Whether you are using Windows
* [ ] Whether you are using Chrome
```dart
@Component(
  selector: 'orcamento_form',
  styles: [],
  templateUrl: 'orcamento_form_component.html',
  directives: [    
    coreDirectives,
    formDirectives,
    MdToast,
    routerDirectives,
    MaterialButtonComponent,
    MaterialSelectComponent,
    MaterialSelectItemComponent,
    MaterialCheckboxComponent,
    AutoDismissDirective,
    AutoFocusDirective,
    MaterialIconComponent,
    MaterialButtonComponent,
    MaterialTooltipDirective,
    MaterialDialogComponent,
    ModalComponent,
    DataTableComponent,
    displayNameRendererDirective,
    EmpresaListComponent,
    TextMaskDirective,
    AnoValidator,
    DateTimeValueAccessor,
    MoneyMaskDirective
  ],
  exports: [RoutePaths, Routes],    
)
class OrcamentoFormComponent   {
  
  final Location _location ;
 
  OrcamentoFormComponent( this._location);

  
}
```

```yaml
name: siscec2browser
description: A web app that uses AngularDart Components
version: 0.0.1

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  angular: ^5.3.0
  angular_components: ^0.13.0
  angular_forms: ^2.0.3
  angular_router: ^2.0.0-alpha
  http: ^0.12.0
  stream_transform: ^0.0.19
  sass_builder: ^2.1.3
  firebase: ^5.0.4
  firebase_dart_ui: ^0.1.1
  js: ^0.6.1+1
  money: ^0.2.1
  decimal: ^0.3.4


dev_dependencies:
  angular_test: ^2.3.0
  build_runner: ^1.6.2
  build_test: ^0.10.3
  build_web_compilers: ^2.1.0
  pedantic: ^1.7.0
  test: ^1.6.0

 ```
