### ISSUE TITLE
Angular and build_runner version solving failed

### ISSUE THREAD

**Issue by fabryx92** [dart-lang/angular#1857]
Thank you for taking the time to file an issue!

In order to route, prioritize, and act on this as soon as possible please include:

* Dart VM version: 2.4.0 (Wed Jun 19 11:53:45 2019 +0200) on "macos_x64"
* AngularDart Version 5.3.0
* macOS
* Chrome

I'm trying to add a dependency with this `pubspec.yaml`

```yaml
dependencies:
  built_value: 6.2.0
  equatable: 0.2.5

dev_dependencies:
  pedantic: ^1.7.0
  build_runner: 1.0.0
  built_value_generator: 6.2.0
```

But the operation failed with this error message:
> Because angular 5.3.0 depends on build_config >=0.2.6 <0.4.0 and build_runner >=1.3.4 <1.6.5 depends on build_config >=0.4.0 <0.4.1, angular 5.3.0 is incompatible with build_runner >=1.3.4 <1.6.5.
(1) So, because build_runner >=1.2.0 <1.2.6 depends on build_daemon ^0.2.0 and build_runner >=0.9.1+1 <1.2.4 depends on build_resolvers ^0.2.0, if angular 5.3.0 and build_runner >=0.9.1+1 <1.2.6-∞ or >=1.3.4 <1.6.5-∞ then build_daemon ^0.2.0 or build_resolvers ^0.2.0.
