### ISSUE TITLE
import 'package:angular_forms/angular_forms.dart' error

### ISSUE THREAD

**Issue by gotamafandy** [dart-lang/angular#1873]
Thank you for taking the time to file an issue!

In order to route, prioritize, and act on this as soon as possible please include:

* [ 2.6.1 ] Dart SDK Version (`dart --version`)
* [ ^6.0.0-alpha+1 ] AngularDart Version (i.e. `4.0.0`, `5.0.0-alpha+5`, `MASTER`)
* [ macOS ] Whether you are using Windows, macOS, or Linux (if applicable)
* [ Chrome ] Whether you are using Chrome, Safari, Firefox, Edge (if applicable)
* [ ] Any other packages or constraints we should know about

pubspect.yaml
```
name: angular_app
description: Tour of Heroes
version: 0.0.1

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  angular: ^6.0.0-alpha+1
  angular_forms: ^2.1.4           
  
dev_dependencies:
  angular_test: ^2.4.0
  build_runner: ^1.5.1
  build_test: ^0.10.8
  build_web_compilers: ^2.1.0
  test: ^1.6.4

```

app_component.dart
```
import 'package:angular/angular.dart';
import 'package:angular_forms/angular_forms.dart';
import 'model/hero.dart';

@Component(
  selector: 'my-app',
  template: '''
    <div>
      <label>name: </label>
      
    </div>
  ''',
  
)
class AppComponent {
  final title = 'Tour of Heroes';
  Hero hero = Hero(1, 'Windstorm');
}

```

importing angular_forms.dart resulting in build error:

```
Please check the following imports:

`import 'package:angular_forms/angular_forms.dart';` from angular_app|lib/app_component.dart at 2:1

[SEVERE]build_web_compilers:entrypoint on web/main.dart: Unable to find modules for some sources, this is usually the result of either a
bad import, a missing dependency in a package (or possibly a dev_dependency
needs to move to a real dependency), or a build failure (if importing a
generated file).

Please check the following imports:

`import 'package:angular_forms/angular_forms.dart';` from angular_app|lib/app_component.dart at 2:1

[INFO] Running build completed, took 171ms
[INFO] Caching finalized dependency graph completed, took 119ms
[SEVERE] Failed after 295ms
```

----

For questions consider using Stack Overflow instead:
https://stackoverflow.com/questions/tagged/angular-dart

Also consider our Gitter channel for light-weight/quick discussions:
https://gitter.im/dart-lang/angular

-----

**Comment by gotamafandy** [comment]
Updating pubspect.yaml resolved the issue

name: angular_app
description: Tour of Heroes
version: 0.0.1

environment:
  sdk: '>=2.2.0 <3.0.0'

```
dependencies:
  angular: ^6.0.0-alpha+1
  angular_forms: ^2.1.4           
  
dev_dependencies:
  angular_test: ^2.4.0
  build_runner: ^1.7.2
  build_test: ^0.10.9+1
  build_web_compilers: ^2.1.0
  test: ^1.9.4
```
