### ISSUE TITLE
I can't navigate directly to a parent route

### ISSUE THREAD

**Issue by insinfo** [dart-lang/angular#1881]
I can't navigate directly to a parent route like the one below: "http://127.0.0.1:8080/#/home/lives"
I can only navigate to the "/ lives" page if I first navigate to "/ home"
I have two areas in the app one is a public area and the other is an area that is only accessible via authentication, so I have two router-outlets

if I navigate straight to "/ home / lives" everything is blank

* [x] Dart SDK Version 
2.7.0 (Fri Dec 6 16:26:51 2019 +0100) on "windows_x64"
* [x] AngularDart Version 
5.3.1
* [x] Whether you are using Windows, macOS, or Linux (if applicable)
 Windows 10 v 1903, macOS Catalina end Debian 10
* [x] Whether you are using Chrome, Safari, Firefox, Edge (if applicable)
Chrome

##### home_component.html
![image](https://user-images.githubusercontent.com/12227024/73754963-08d8de00-4744-11ea-815b-c1926163326b.png)

<details><summary>home_component.html</summary>

```html
<div class="page-content" >
    <div class="content-wrapper">
        <!-- Page header -->
        <div class="page-header page-header-light">
            <div class="page-header-content header-elements-md-inline">
                <div class="page-title d-flex">
                    <h4>
                        <i class=""></i>
                        <span class="font-weight-semibold">Admin</span>                      
                    </h4>                
                </div>
                <div class="header-elements menu-principal" [ngClass]="displayMenu ? 'teste' : 'd-none'">
                    <div class="d-flex justify-content-center">
                        <a [routerLink]="RoutePaths.lives.toUrl()" [routerLinkActive]="'active'"
                            class="btn btn-link btn-float font-size-sm font-weight-semibold text-default legitRipple">
                            <i class="icon-stack-play text-pink-300"></i>
                            <span>Live</span>
                        </a>                                                
                    </div>
                </div>
            </div>
        </div>
        <!-- /Page header -->
        <!-- content area -->
        <div >
            <router-outlet [routes]="Routes.all"></router-outlet>
        </div>
        <!-- /Content area -->       
    </div>
</div>
```

</details>

<details><summary>route_paths.dart</summary>

```dart
class RoutePaths {
  static final lives = RoutePath(path: 'lives', parent: PublicRoutePaths.home);
  static final liveEdit = RoutePath(path: '${lives.path}/edit/:id', parent: PublicRoutePaths.home);
  static final liveNew = RoutePath(path: '${lives.path}/new', parent: PublicRoutePaths.home);
}

class PublicRoutePaths {
  //public routes
  static final livePublic = RoutePath(path: 'livePublic');
  static final home = RoutePath(path: 'home');
}


```

</details>

![image](https://user-images.githubusercontent.com/12227024/73755739-412cec00-4745-11ea-886f-bce45a4f71c0.png)

<details><summary>routes.dart</summary>

```dart

  static final lives = RouteDefinition(
    routePath: RoutePaths.lives,
    component: live_list_template.LiveListComponentNgFactory,
  );

  static final liveEdit = RouteDefinition(
    routePath: RoutePaths.liveEdit,
    component: live_form_template.LiveFormComponentNgFactory,
  );

  static final liveNew = RouteDefinition(
    routePath: RoutePaths.liveNew,
    component: live_form_template.LiveFormComponentNgFactory,
  );
 static final all = <RouteDefinition>[ 
    lives,
    liveNew,
    liveEdit  
  ];
}

class PublicRoutes {
  static final home = RouteDefinition(
      routePath: PublicRoutePaths.home, component: home_template.HomeComponentNgFactory, useAsDefault: true);

  static final livePublic = RouteDefinition(
    routePath: PublicRoutePaths.livePublic,
    component: live_public_template.LivePublicComponentNgFactory,
  );

  static final all = <RouteDefinition>[
    home,
    livePublic,
  ];
}
```

</details

<details><summary>app_component.html</summary>

```html
<router-outlet [routes]="PublicRoutes.all"></router-outlet>
```
</details

<details><summary>home_component.html</summary>

```html
   <router-outlet [routes]="Routes.all"></router-outlet>
```
</details

##### pubspec.yaml
```yaml
name: appsescveraobrowser
description: A web app that uses AngularDart Components
version: 0.0.1

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  angular: ^5.3.1
  angular_components: ^0.13.0+1
  angular_forms: 
  angular_router: ^2.0.0-alpha+19
  http: ^0.12.0+2
  stream_transform: ^0.0.19
  sass_builder: ^2.1.3
  firebase: ^5.0.2
  firebase_dart_ui: ^0.1.2  
  js: ^0.6.1+1
  spreadsheet_decoder: ^1.1.0
  queries: ^0.1.12   
  essential_components: ^0.1.75
    
dev_dependencies:
  angular_test: ^2.3.0
  build_runner: ^1.7.2
  build_test: ^0.10.9+1
  build_web_compilers: ^2.7.1
  pedantic: ^1.8.0
  test: ^1.6.0

```
