### ISSUE TITLE
Fail on compilation if users are importing from angular/src

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular#497]
This could initially be introduced with a flag that allows unsafe imports for 4.0. Example:

```yaml
transformers:
  angular:
    allow_unsafe_imports: true # Opt-in to allowing lib/src imports without a build failure.
```

WDUT @kevmoo @jakemac53 @hterkelsen?
