### ISSUE TITLE
Enable tests that require code generation to run on travis

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular#499]
It doesn't look like we run any code generation right now: https://github.com/dart-lang/angular/blob/master/_tests/pubspec.yaml.

**Comment by matanlurey** [comment]
Pub serve never completes with this `pubspec.yaml` for `_tests`:

```yaml
name: _tests
author: Dart Team <web@dartlang.org>
description: Tests for AngularDart.
environment:
  sdk: '>=1.24.0 <2.0.0'
dev_dependencies:
  angular: 4.0.0-dev
  angular_test: '^1.0.0-beta'
  build_runner: ^0.3.4
  build_test: ^0.6.0
  mockito: '>=0.11.0 <3.0.0'
  source_span: ^1.4.0
  test: ^0.12.6

# DO NOT REMOVE. We don't publish this package, it is just for testing.
dependency_overrides:
  angular:
    path: ../angular
  angular_test:
    path: ../angular_test

transformers:
  # Run the code generator on the entire package.
  - angular

  # Allow test to proxy-load files so we can run AoT tests w/ pub serve.
  - test/pub_serve:
      $include: test/**_test.dart
```

Any idea how I can debug this @jakemac?
