### ISSUE TITLE
4.0.0-alpha entry_points no longer accepts a single value

### ISSUE THREAD

**Issue by leonsenft** [dart-lang/angular#510]
Prior to 4.0.0-alpha, the standard way of specifying your application's entry point was as follows:
```yaml
transformers:
  - angular:
      entry_points: web/main.dart
```
Now the transformer insists `entry_points` take a list of values. This likely breaks most of our users, and  requires updating tooling such as [Stagehand](http://stagehand.pub/). Instead I propose we revert this behavior and accept single values.
