### ISSUE TITLE
pub serve/build fails with v4: No top-level method 'strings.isNotEmpty' declared.

### ISSUE THREAD

**Issue by enyo** [dart-lang/angular#515]
I have upgrade from angular 3 to angular `4.0.0-alpha` and am now unable to `pub serve/build` my project.

I get many errors like these when running:

```
[BuilderTransformer: GeneratorBuilder:[TemplateGenerator] on angular|lib/angular.dart]:
Error running TemplateGenerator for angular.
Error: NoSuchMethodError: No top-level method 'strings.isNotEmpty' declared.
Receiver: top-level
Tried calling: strings.isNotEmpty("angular")
Stack Trace:
#0      NoSuchMethodError._throwNew (dart:core-patch/errors_patch.dart:196)
#1      buildGeneratedCode (package:angular/src/source_gen/template_compiler/code_builder.dart:32:7)
#2      TemplateGenerator.generate.<anonymous closure> (package:angular/src/source_gen/template_compiler/generator.dart:33:14)
<asynchronous suspension>
#3      _rootRun (dart:async/zone.dart:1120)
#4      _CustomZone.run (dart:async/zone.dart:1001)
#5      runZoned (dart:async/zone.dart:1467)
#6      TemplateGenerator.generate (package:angular/src/source_gen/template_compiler/generator.dart:30:12)
<asynchronous suspension>
#7      _processUnitMember (package:source_gen/src/builder.dart:179:35)
<asynchronous suspension>
#8      _generate (package:source_gen/src/builder.dart:170:12)
<asynchronous suspension>
#9      GeneratorBuilder._generateForLibrary (package:source_gen/src/builder.dart:93:15)
<asynchronous suspension>
#10     GeneratorBuilder.build (package:source_gen/src/builder.dart:78:11)
<asynchronous suspension>
#11     runBuilder.buildForInput (package:build/src/generate/run_builder.dart:35:21)
<asynchronous suspension>
#12     MappedListIterable.elementAt (dart:_internal/iterable.dart:413)
#13     ListIterator.moveNext (dart:_internal/iterable.dart:342)
#14     Future.wait (dart:async/future.dart:355)
#15     runBuilder.<anonymous closure> (package:build/src/generate/run_builder.dart:41:31)
#16     _rootRun (dart:async/zone.dart:1120)
#17     _CustomZone.run (dart:async/zone.dart:1001)
#18     runZoned (dart:async/zone.dart:1467)
#19     scopeLog (package:build/src/builder/logging.dart:12:38)
#20     runBuilder (package:build/src/generate/run_builder.dart:41:9)
<asynchronous suspension>
#21     BuilderTransformer.apply (package:build_barback/src/transformer/transformer.dart:81:11)
<asynchronous suspension>
#22     _EagerTransformerWrapper.apply (package:angular/src/transform/common/eager_transformer_wrapper.dart:21:50)
#23     _serializeTransformer.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:$pub/serialize/transformer.dart:31:30)
#24     new Future.sync (dart:async/future.dart:206)
#25     _serializeTransformer.<anonymous closure>.<anonymous closure> (package:$pub/serialize/transformer.dart:30:20)
#26     respond.<anonymous closure> (package:$pub/serialize.dart:150:33)
#27     new Future.sync (dart:async/future.dart:206)
#28     respond (package:$pub/serialize.dart:150:7)
#29     _serializeTransformer.<anonymous closure> (package:$pub/serialize/transformer.dart:17:5)
#30     _RootZone.runUnaryGuarded (dart:async/zone.dart:1307)
#31     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#32     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#33     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:796)
#34     _StreamController._add (dart:async/stream_controller.dart:667)
#35     _StreamController.add (dart:async/stream_controller.dart:613)
#36     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:151)
```

The relevant parts of my `pubspec.yaml` are:

```yaml
environment:
  sdk: ^1.24.0

dependencies:
  # [ ... ]
  angular: ^4.0.0-alpha
  # [ ... ]

transformers:
- transform_sass
- angular:
    entry_points:
    - web/angular.dart
    - web/dashboard.dart
    - web/admin.dart
- $dart2js:
    minify: true
    commandLineOptions:
    - --enable-experimental-mirrors
# This rewrites the .dart imports to .js imports, removing unnecessary 404 requests.
- dart_to_js_script_rewriter
web:
  compiler:
    debug: dartdevc
```
