### ISSUE TITLE
Angular transformer deadlocks on `_tests`

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular#517]
After a few hours of debugging with @alorenzen, I've narrowed it down to here:

```dart
      await crawlImports(
          inputs,
          (id) => transform
              .readInputAsString(toBarbackAssetId(id))
              .catchError((_) => null));
```

... from `build_barback`. AFAICT, this was added by @natebosch for an internal customer that uses pub, but this same code causes circular dependencies in Angular itself to never succeed building when using with the `_tests` package:

```yaml
// Add this to _tests/pubspec.yaml at the bottom
transformers:
  - angular/transform/reflection_remover:
      $include: test/**_test.dart
  - angular/transform/codegen
  - test/pub_serve:
      $include: test/**_test.dart
```

I don't know if its safe to remove this, or make it a flag, or what the proper fix should be.
