### ISSUE TITLE
Angular4 can't resolve any directives

### ISSUE THREAD

**Issue by zoechi** [dart-lang/angular#538]
```
11:06 $ pub serve
Loading source assets... 
Loading dart_sass_transformer, angular, test/pub_serve and dart_to_js_script_rewriter transformers... 
Serving myProject web  on http://localhost:8080
Serving myProject test on http://localhost:8081
[BuilderTransformer: GeneratorBuilder:[TemplateGenerator] on myProject|lib/src/components/app/app_component.dart]:
Error running TemplateGenerator for .
Error: Bad state: Failed to parse @Component annotation for AppComponent:
One or more of the following arguments were unresolvable: 
* CORE_DIRECTIVES
* ConversationsPagerDirective
* materialDirectives
* ROUTER_DIRECTIVES
* ToolbarComponent
* ConversationsComponent
* virtualScrollDirectives
The root cause could be a mispelling, or an import statement that 
looks valid but is not resolvable at build time. Bazel users should 
check their BUILD file to ensure all dependencies are listed.
```

for

```dart
@Component(
  selector: 'datingnode-app',
  styleUrls: const ['app_component.css'],
  templateUrl: 'app_component.html',
  directives: const <dynamic>[
    CORE_DIRECTIVES,
    ConversationsPagerDirective,
    materialDirectives,
    ROUTER_DIRECTIVES,
    ToolbarComponent,
    ConversationsComponent,
    virtualScrollDirectives,
  ],
  providers: const <dynamic>[
    materialProviders,
  ],
)
@RouteConfig(appRoutes)
class AppComponent {
```

**Comment by matanlurey** [comment]
So this bailout occurs whenever we detect something resolved as either `null` or `dynamic` within your directives (https://github.com/dart-lang/angular/blob/be6997385a0dcbb907b7971f9dcc0bcfdaa02d61/angular/lib/src/source_gen/template_compiler/find_components.dart#L112):

```dart
  if (directives.isEmpty && annotation != null) {
      // Two reasons we got to this point:
      // 1. The directives: const [ ... ] list was empty or omitted.
      // 2. One or more identifiers in the list were not resolved, potentially
      //    due to missing imports or dependencies.
      //
      // The latter is specifically tricky to debug, because it ends up failing
      // template parsing in a similar way to #1, but a user will look at the
      // code and not see a problem potentially.
      for (final argument in annotation.annotationAst.arguments.arguments) {
        if (argument is NamedExpression &&
            argument.name.label.name == _directivesProperty) {
          final values = argument.expression as ListLiteral;
          if (values.elements.isNotEmpty &&
              // Avoid an edge case where all of your directives: ... entries
              // are just empty lists. Not likely to happen, but might as well
              // check anyway at this point.
              values.elements.every((e) => e.staticType?.isDynamic != false)) {
            // We didn't resolve something.
            _failFastOnUnresolvedTypes(values.elements, element);
          }
        }
      }
    }
```

Unfortunately the analyzer drops information that would be useful for us to debug this in the compiler (i.e. `could not resolve import x`), so this is the best error message I could produce.

**Comment by zoechi** [comment]
DartAnalyzer doesn't show any import issues :-/

**Comment by matanlurey** [comment]
Are you relying on `RESOLVED_IDENTIFIERS` (i.e. was this non-empty before)?

**Comment by zoechi** [comment]
Yes, `RESOLVED_IDENTIFIERS` was required

```yml
    resolved_identifiers:
        BaseClient: 'package:http/http.dart'

        ClientCache: 'package:datingnode_api/datingnode_api.dart'
        DeviceCapabilities: 'package:datingnode_api/src/models/device_capabilities.dart'

        ConversationsPager: 'package:my_project/my_project.dart'
        ApiService: 'package:my_project/src/services/api_service.dart'
        NavigationService: 'package:my_project/src/services/navigation_service.dart'
        Pager: 'package:my_project/src/components/virtual_scroll/virtual_scroll.dart'
        PublicSearchPager: 'package:my_project/my_project.dart'
        SearchPager: 'package:my_project/my_project.dart'
        SearchPagerShared: 'package:my_project/my_project.dart'
        VirtualScrollService: 'package:my_project/src/components/virtual_scroll/virtual_scroll_service.dart'
```
I don't know why they were required. I just added them when `pub serve` complained about not being able to resolve them.
