### ISSUE TITLE
Upgrading to angular 4.0.0 -alpha Issue

### ISSUE THREAD

**Issue by pravissimo** [dart-lang/angular#564]
Trying to upgarade my app to the latest version, however console is returning an exception:

```
_Incompatible version constraints on csslib:
- angular 4.0.0-alpha depends on version ^0.14.0
- angular2 3.1.0-beta depends on version ^0.13.4
- html 0.13.2 depends on version >=0.13.2 <0.15.0_

```
my pubspec:

```
environment:
  sdk: '>=1.23.0 <2.0.0'

dependencies:
  wnioski:
    path: ../wnioski
  angular: 4.0.0-alpha
  angular_compiler: ^0.1.0-dev
  polymer: 1.0.0-rc.19
  polymer_elements: 1.0.0-rc.9

dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1

transformers:
- polymer:
    entry_points: web/index.html
- angular:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
- dart_to_js_script_rewriter
```
