### ISSUE TITLE
Update angular_test README.md

### ISSUE THREAD

**Issue by eredo** [dart-lang/angular#622]
Using the provided `pubspec.yaml` provided in the [README.md](https://github.com/dart-lang/angular/blob/master/angular_test/README.md) causes `pub build` on 4.0 to hang because of `- angular/transform/codegen` and `- angular/transform/reflection_remover` transformers. 
The webdev documentation on [how to test components](https://webdev.dartlang.org/angular/guide/testing/component/basics#!#toh-0pubspecyaml-transformers) already contains the proper `pubspec.yaml` file which no longer causes an issue.

Correct pubspec.yaml for testing:

```yaml
transformers:
- angular:
    entry_points:
    - web/main.dart
    - test/**_test.dart
- test/pub_serve:
    $include: test/**_test.dart
- dart_to_js_script_rewriter
```
