### ISSUE TITLE
angular_router: 2.0.0-alpha compatible with angular 5.0.0-alpha?

### ISSUE THREAD

**Issue by 4cm4k1** [dart-lang/angular#676]
Is `angular_router` (2.0.0-alpha) compatible with `angular` (5.0.0-alpha), and if so, how can I do a manual dependency override?

**Comment by matanlurey** [comment]
I don't see any reason why not. You can add this to your `pubspec.yaml`:

```dart
dependency_overrides:
  angular: ^5.0.0-alpha
```

... and try it out. Please let us know if you have other questions :)

**Comment by 4cm4k1** [comment]
Thank you @matanlurey! I appreciate all the good work you all are doing. 😄

**Comment by abnerh69** [comment]
Hi **@matanlurey** today I started trying your advice, in my project pubspec.yaml file:

```
environment:
  sdk: '>=1.24.0 <2.0.0'
dependencies:
  angular: ^5.0.0-alpha
  angular_components: ^0.9.0-alpha
  angular_forms: ^1.0.1-alpha
  angular_router: ^2.0.0-alpha
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  sass_builder: ^1.0.0

```
but Resolving dependencies...
Incompatible version constraints on angular:
- angular_components 0.9.0-alpha depends on version 5.0.0-alpha
- angular_forms 1.0.1-alpha depends on version ^5.0.0-alpha
- angular_router 2.0.0-alpha depends on version ^4.0.0
- huastecappadmin depends on version ^5.0.0-alpha
Process finished with exit code 1

Any Idea?
