### ISSUE TITLE
How to solve angular_router: ^2.0.0-alpha incompatibility with angular 5.0.0-alpha?

### ISSUE THREAD

**Issue by abnerh69** [dart-lang/angular#681]
Today I started trying advice from **@matanlurey** in https://github.com/dart-lang/angular/issues/676.   In my project pubspec.yaml file:

```
environment:
  sdk: '>=1.24.0 <2.0.0'
dependencies:
  angular: ^5.0.0-alpha
  angular_components: ^0.9.0-alpha
  angular_forms: ^1.0.1-alpha
  angular_router: ^2.0.0-alpha
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  sass_builder: ^1.0.0

```
but Resolving dependencies...
```
Incompatible version constraints on angular:
- angular_components 0.9.0-alpha depends on version 5.0.0-alpha
- angular_forms 1.0.1-alpha depends on version ^5.0.0-alpha
- angular_router 2.0.0-alpha depends on version ^4.0.0
- huastecappadmin depends on version ^5.0.0-alpha
Process finished with exit code 1
```

Any Idea?
