### ISSUE TITLE
Reused components lose scroll position

### ISSUE THREAD

**Issue by leonsenft** [dart-lang/angular#752]
If a routed component has an overflow element, when the route is reused, the scroll position in that element is lost.

If you have a component with the following template and styles

```html
<div class="scroll">
  <div class="scroll-content">
    Scroll me!
  </div>
</div>
```
```css
.scroll {
  width: 100px;
  height: 100px;
  overflow: scroll;
}

.scroll-content {
  height:2000px;
}
```

located at route 

```
/detail/:id
```

with

```dart
@override
Future<bool> canReuse(_, __) async => true;
```

Navigate to `#/detail/1`, then to `#/detail/2`. Scroll the div and hit the back button and notice the scroll position resets.

Supposedly the old router retained the current scroll position instead of resetting it.
